### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by jamal1299**
Vowel and Consonant Checker is added.

### CODE REVIEW

**Review by mediocre9 — CHANGES_REQUESTED** [review]
@jamal1299  The program might not be able to run properly... Because `#include <iostream>` is not declared **secondly dead code is also present at the last line** and third issue is that `return 0` is also not present. Submit full code....**_By the way youre doing great job Happy Learning. . ._**

**Comment by jamal1299** [comment]
I am Using online compiler and the code is working

**Comment by mediocre9** [comment]
let me check . . .

**Comment by mediocre9** [comment]
ah i see..... sorry my bad.... your pull request was a patch to the main branch . . .

**Comment by jamal1299** [comment]
Hahah Its Ok , 
is code working or not ?

**Comment by mediocre9** [comment]
> Hahah Its Ok , is code working or not ?

works like a charm! :sunglasses:

**Pull request merged**
